apiVersion: v1
kind: Service
metadata:
  name: pulse-db-external
  namespace: pulse-master-portal
spec:
  type: NodePort
  selector:
    app: pulse-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30307   # SQLyog uses this
